openapi: 3.0.0
info:
  version: "latest"
  title: HEI - tribu
paths:
  /users:
    get:
      tags:
        - Users
      summary: get all users
      operationId: getUsers
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
    post:
      tags:
        - Users
      summary: create users
      operationId: createUsers
      responses:
        '200':
          description: List of users created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateUers'
components:
  schemas:
    CreateUers:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - STUDENT
            - TEACHER
    Users:
      type: object
      properties:
        id:
          type: number
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - STUDENT
            - TEACHER
        gender:
          type: string
          enum:
            - M
            - F
        avatar_link:
          type: string